#! /usr/bin/env python3
#
# Copyright (c) 2014-23 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# This tool provides command line access to:
#
# - discover / login / manage ttbd servers and users of said servers
#
# - managed targets exported by ttbd, so you can power cycle them,
#   access the console, press buttons, ... (so using the ttbd REST
#   HTTP API from the command line).
#
# - other more advanced functions, like getting cookies, etc
#
# This file just a multiplexor of subcommands
#
# Initializes the command line argument, which has a bunch of common
# command line options and then starts importing submodules, running
# for each their CLI setup, which creates subcommands.
#
# Current transitioning CLI initialization from tcfl/target_ext_*.py
# (which are API modules) to tcfl/ui_cli_*.py, so it is clearly
# separated what deals with CLI and what is actually API.
#
# When all that is done, parse the arguments, then the config files,
# and run whatever subcommand has been specified in the command line.
#

if __name__ == "__main__":
    import tcfl.ui_cli_main
    tcfl.ui_cli_main.__main__()
